# Generated by Django 5.2.7 on 2025-10-23 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('post_type', models.CharField(choices=[('lost', 'Kayıp Eşya'), ('found', 'Bulunan Eşya')], max_length=10, verbose_name='İlan Türü')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('resolved', 'Çözüldü'), ('closed', 'Kapalı')], default='active', max_length=10, verbose_name='Durum')),
                ('location', models.CharField(max_length=200, verbose_name='Konum')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='İlçe')),
                ('contact_phone', models.CharField(max_length=15, verbose_name='İletişim Telefonu')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='İletişim E-posta')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='Görsel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('reward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ödül')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Acil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_posts', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'İlan',
                'verbose_name_plural': 'İlanlar',
                'db_table': 'accounts_itempost',
                'ordering': ['-created_at'],
            },
        ),
    ]
