# Generated by Django 5.2.7 on 2025-10-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_itempost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempost',
            name='reward',
        ),
    ]
