# Generated by Django 4.2.26 on 2025-12-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_reward_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempost',
            name='child_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yaş'),
        ),
        migrations.AddField(
            model_name='itempost',
            name='child_eye_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Göz Rengi'),
        ),
        migrations.AddField(
            model_name='itempost',
            name='child_gender',
            field=models.CharField(blank=True, choices=[('erkek', 'Erkek'), ('kız', 'Kız')], max_length=10, null=True, verbose_name='Cinsiyet'),
        ),
        migrations.AddField(
            model_name='itempost',
            name='child_hair_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Saç Rengi'),
        ),
        migrations.AddField(
            model_name='itempost',
            name='child_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Boy (cm)'),
        ),
        migrations.AddField(
            model_name='itempost',
            name='child_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Çocuğun Adı'),
        ),
        migrations.AddField(
            model_name='itempost',
            name='child_physical_features',
            field=models.TextField(blank=True, null=True, verbose_name='Fiziksel Özellikler'),
        ),
        migrations.AddField(
            model_name='itempost',
            name='child_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilo (kg)'),
        ),
        migrations.AddField(
            model_name='itempost',
            name='is_missing_child',
            field=models.BooleanField(default=False, verbose_name='Kayıp Çocuk İlanı'),
        ),
        migrations.AddField(
            model_name='itempost',
            name='last_seen_clothing',
            field=models.TextField(blank=True, null=True, verbose_name='Son Görüldüğünde Üzerindeki Kıyafetler'),
        ),
        migrations.AddField(
            model_name='itempost',
            name='last_seen_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Son Görüldüğü Yer'),
        ),
        migrations.AddField(
            model_name='itempost',
            name='missing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kaybolma Tarihi'),
        ),
    ]
